SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
    STRING varchar(50) := 'MALAYALAM';
    REVERSE VARCHAR(50);
    M1 varchar(50) := ' IS A PALINDROME';
    M2 varchar(50) := ' IS NOT A PALINDROME';
    STR_LEN NUMBER;

BEGIN
    STR_LEN := LENGTH(STRING);
    
    FOR I IN REVERSE 1..STR_LEN LOOP
        REVERSE := REVERSE || SUBSTR(STRING, I, 1);
    END LOOP;
    
    IF (STRING = REVERSE) then
        DBMS_OUTPUT.PUT_LINE(STRING || M1);
    ELSE
        DBMS_OUTPUT.PUT_LINE(STRING || M2);
    END IF;
    
END;
/