SET SERVEROUTPUT ON;

DECLARE
    CURSOR DISPLAY IS
        SELECT * FROM (SELECT  * FROM EMPLOYEES ORDER BY SALARY DESC ) WHERE ROWNUM <= 5;

    EMPREC DISPLAY%ROWTYPE;

BEGIN
    OPEN DISPLAY;
    DBMS_OUTPUT.PUT_LINE('STAFF_ID	NAME	SALARY');
    LOOP
        FETCH DISPLAY INTO EMPREC;
        EXIT WHEN DISPLAY%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE(EMPREC.STAFF_ID || '	' || EMPREC.NAME || '	'  || EMPREC.SALARY || '	' );
    END LOOP;
    
    CLOSE DISPLAY;
END;
/

