SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
    NO_NO_NO EXCEPTION;
    RESULT NUMBER;
    NUM1 NUMBER := 10;
    NUM2 NUMBER := 100;

BEGIN
    RESULT := NUM1 / NUM2;
    
    IF NUM2 = 100 then
        RAISE NO_NO_NO;
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('OUTPUT = ' || RESULT);
    
EXCEPTION
    WHEN ZERO_DIVIDE then
        DBMS_OUTPUT.PUT_LINE('DIVISION BY ZERO IS NOT POSSIBLE!');
    WHEN NO_NO_NO then
        DBMS_OUTPUT.PUT_LINE('DIVISION BY 100 IS NOT ALLOWED!');
        
END;
/