CREATE OR REPLACE PACKAGE mathPack AS

    -- ADD TWO NUMBERS
    FUNCTION addNum(num1 NUMBER, num2 NUMBER) RETURN NUMBER;

    -- SUBTRACT TWO NUMBERS
    FUNCTION subtractNum(num1 NUMBER, num2 NUMBER) RETURN NUMBER;

    -- MULTIPLY TWO NUMBERS
    FUNCTION multiplyNum(num1 NUMBER, num2 NUMBER) RETURN NUMBER;

    -- DIVIDE TWO NUMBERS
    FUNCTION divideNum(num1 NUMBER, num2 NUMBER) RETURN NUMBER;

    -- SQUARE OF A NUMBER
    FUNCTION square(num IN NUMBER) RETURN NUMBER;

END mathPack;
/